update

diff --git a/.github/workflows/CI-CD.yml b/.github/workflows/CI-CD.yml
--- a/.github/workflows/CI-CD.yml
+++ b/.github/workflows/CI-CD.yml
@@ -45,46 +45,46 @@ jobs:
       - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
       - run: echo "🖥️ The workflow is now ready to test your code on the runner."
 
-      - name: List files in the repository
-        run: |
-          ls ${{ github.workspace }}
-
       - name: Create directory in the repository
         run: |
           mkdir -p ${{ github.workspace }}/htmlcov
           chmod 777 ${{ github.workspace }}/htmlcov
 
-      # # Start ChromaDB Service
-      # - name: Start ChromaDB Container
-      #   run: |-
-      #     docker run -d --rm \
-      #       --name chromadb \
-      #       -p 8000:8000 \
-      #       chromadb/chromadb:latest
+      # Start ChromaDB Service
+      - name: Start ChromaDB Container
+        run: |-
+          docker run -d --rm \
+            --name chromadb \
+            -p 8000:8000 \
+            chromadb/chroma:latest
           
-      # # Wait for ChromaDB to be ready
-      # - name: Wait for ChromaDB to Start
-      #   run: |-
-      #     for i in {1..30}; do
-      #       if curl -s http://localhost:8000/health >/dev/null; then
-      #         echo "ChromaDB is ready!"
-      #         exit 0
-      #       fi
-      #       echo "Waiting for ChromaDB to be ready..."
-      #       sleep 5
-      #     done
-      #     echo "ChromaDB failed to start within the timeout period."
-      #     exit 1
+      # Wait for ChromaDB to be ready
+      - name: Wait for ChromaDB to Start
+        run: |-
+          for i in {1..30}; do
+            if curl -s http://localhost:8000/health >/dev/null; then
+              echo "ChromaDB is ready!"
+              exit 0
+            fi
+            echo "Waiting for ChromaDB to be ready..."
+            sleep 5
+          done
+          echo "ChromaDB failed to start within the timeout period."
+          exit 1
 
       - name: Build Deployment Container
         run: |-
           cd ${{ github.workspace }}/test_action/
           docker build -t m4_deployment -f Dockerfile .
 
+      - name: List files in the repository
+        run: |
+          ls ${{ github.workspace }}
+
       - name: Run Deploy App
         run: |-
-          # docker run --rm --name m4_deployment \
-          docker-compose run --rm --service-ports m4_deployment \
+          # docker-compose run --rm --service-ports m4_deployment \
+          docker run --rm --name m4_deployment \
             -v /var/run/docker.sock:/var/run/docker.sock \
             -v $HOME/.ssh:/home/app/.ssh \
             -v ${{ github.workspace }}/test_action:/test_action \
